import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ninja List | Home</title>
        <meta name="keywords" content="ninjas" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.title}>
        <h1>HomePage</h1>
        <p className={styles.text}>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum blanditiis optio sunt? Dignissimos, laboriosam a officiis ad esse facilis aperiam consequuntur soluta, consectetur, nulla doloremque dicta molestiae. Possimus, tempora accusantium.</p>
        <p className={styles.text}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi inventore facilis, reiciendis veritatis sunt eaque eius mollitia illum quia veniam deleniti id cum cumque pariatur illo iure dicta, impedit consequuntur.</p>
        <Link href="/ninjas" className={styles.btn}>See Ninja Listing</Link>
      </main>
    </>
  )
}
